### PR TITLE
Add redshift external tables

### PR DESCRIPTION
**Pull request by danieldiamond**
## Description

Existing `data-diff` redshift capabilities are unable to read external tables. These are found in the `svv_external_columns` table. 

Original thought was to add a database flag `-e --external-table` but I don't believe flags can be specific to one database connection and not the other. A simpler approach is to simply query the external tables in redshift if none was found in the redshift one.

* Adding `select_external_table_schema` in redshift sqeleton
* Add condition to query redshift external tables if no results were found in the redshift database.

### CODE REVIEW

**Comment by erezsh** [comment]
@danieldiamond  Made a small change so the code is more modular.

https://github.com/datafold/data-diff/pull/345

Please check that it works for you, and I'll merge it in.

If you can write a test for it, that would be even better!  (maybe [here](https://github.com/datafold/data-diff/blob/master/tests/test_api.py))

**Comment by danieldiamond** [comment]
@erezsh was running into issues with the `query_table_schema` function, updated here

**Comment by erezsh** [comment]
(don't worry about the CI error, it's a problem on our end)

**Comment by erezsh** [comment]
Thank you for contributing!

**Pull request merged**
