### PR TITLE
fix link to docs

### PR DESCRIPTION
**Pull request by leoebfolsom**

### CODE REVIEW

**Comment by erezsh** [comment]
I think the link is more correct the way it is now.

**Comment by erezsh** [comment]
What I mean, we should change it to https://docs.datafold.com/os_diff/how_to_use/how_to_use_with_command_line

Although I consider it a big flaw that https://docs.datafold.com/os_diff/how_to_use/ is an invalid URL

**Comment by leoebfolsom** [comment]
@erezsh please change it to https://docs.datafold.com/os_diff/how_to_use/how_to_use_with_command_line if you think that's better and then merge, and then we can discuss on Monday. We cannot wait all weekend to change a broken link in the readme, and I'm not available to debate right now. Thank you.

**Comment by leoebfolsom** [comment]
@erezsh since I didn't hear from you, I updated the link based on your request.

**Comment by erezsh** [comment]
Thanks!

**Pull request merged**
