### PR TITLE
Add support for Trino

### PR DESCRIPTION
**Pull request by danthelion**
Mainly based on the Presto integration to serve as a starting point for future development.

### CODE REVIEW

**Comment by danthelion** [comment]
@erezsh Fixed the Poetry dependencies.

**Comment by erezsh** [comment]
Hi @danthelion , thanks for making a contribution!

The next step is be to add Trino to the `DATABASE_TYPES` dict in https://github.com/datafold/data-diff/blob/master/tests/test_database_types.py#L186, and run the tests against it. Make sure it's activated along with at least one other database, for example postgresql or mysql.

A few points:

- Make sure you add as many distinct types as possible. However, no need to cover all the possible variations of them.

- It might take a few minutes to run. If that becomes an issue, you can run the tests with `unittest-parallel`.

We're going to write a comprehensive guide for contributors real soon. But meanwhile, if you have any questions at all, I'll be happy to answer them.

**Comment by erezsh** [comment]
Looks like the port is already used. Perhaps by Presto?

**Comment by erezsh** [comment]
Just one note about the PR, please make trino optional, like the rest. i.e.

```toml
trino = { version = "^0.314.0", optional = true }
```

**Comment by erezsh** [comment]
Hi @danthelion ,

I opened a new PR to fix a few minor things and to make sure the tests run in the CI. (#162 )

I'm getting this error from Trino:

```
trino.exceptions.HttpError: error 401: b'Basic authentication or X-Presto-User must be sent'
```

(See here: https://github.com/datafold/data-diff/runs/7309529815?check_suite_focus=true)

I don't have this issue when I run it locally. Any idea what's the problem and how to fix it?

**Comment by erezsh** [comment]
P.S. I'm using `TEST_TRINO_CONN_STRING = "trino://presto@127.0.0.1/postgresql/public"`

**Comment by danthelion** [comment]
@erezsh thanks for looking into this! I added the fixes to this branch. Could you try running the CI with `TEST_TRINO_CONN_STRING="trino://postgres@127.0.0.1:8081/postgresql/public"` (The user and port are different) - I think the Trino client is trying to talk to the Presto service this way

**Comment by erezsh** [comment]
Keep in mind these tests are still running with `(WARNING) root -- Connection to <class 'data_diff.databases.trino.Trino'> not configured`

**Comment by erezsh** [comment]
Now I'm getting `trino.exceptions.TrinoExternalError: TrinoExternalError(type=EXTERNAL, name=JDBC_ERROR, message="The connection attempt failed.", query_id=20220713_082053_03808_dtucz)`

Does it mean it couldn't find the server?

**Comment by erezsh** [comment]
But it's happening here:

```
  File "/home/runner/work/data-diff/data-diff/data_diff/databases/trino.py", line 58, in _query
    return c.fetchone()
```

**Pull request merged**
