### PR TITLE
Materialize: rename and reorder columns

### PR DESCRIPTION
**Pull request by erezsh**

### CODE REVIEW

**Comment by leoebfolsom** [comment]
@erezsh does this also address not only the ordering, but also the point that I raised in Slack that

> column names alternately use `a/b` and `1/2` to represent the left and right tables

Will they all now materialize as `a/b` instead of `1/2`?

**Comment by erezsh** [comment]
@leoebfolsom Let me know if it behaves as you'd expect, so I can merge it in.

**Comment by leoebfolsom** [comment]
This works as expected--thank you! @erezsh

**Review by leoebfolsom — APPROVED** [review]

**Comment by leoebfolsom** [comment]
@erezsh please merge when you're ready.

**Pull request merged**
