### PR TITLE
Support MSSQL for cross-database diffs

### PR DESCRIPTION
**Pull request by nolar**
TODOs:

* [ ] Deploy a sample MS SQL Server database.
* [ ] Add tests for MS SQL Server.
* [ ] Uncomment other tests in `TEST_DATABASES`.

### CODE REVIEW

**Review by dlawin — APPROVED** [review]

**Comment by dlawin** [comment]
re: TODOs, this will be handled as a release candidate and TODOs handled separately

**Comment by dlawin** [comment]
#51

**Comment by sungchun12** [comment]
@bbrewington Great timing, I'm going to do just that in a little bit!

**Comment by sungchun12** [comment]
It's officially on the homepage!

**Comment by bbrewington** [comment]
@sungchun12 AMAZING - thanks!

Heads up website docs need updated as well: https://docs.datafold.com/reference/open_source/cli/?database=other#connection-methods

image

**Pull request merged**
