### PR TITLE
allow joindiff across bigquery projects

### PR DESCRIPTION
**Pull request by segv**

### CODE REVIEW

**Comment by segv** [comment]
> Why not just follow the simple way we implemented it for snowflake, where you use the same database connection, **but then specify a different project in the table path?**

My brain just didn't make the connection that this was what you were talking about. PR updated.

**Comment by erezsh** [comment]
Looking better! I believe the change in `info_tree.py` isn't necessary anymore, right?

**Comment by erezsh** [comment]
(don't worry about the CI error, it's a problem on our end)

**Comment by segv** [comment]
I reverted the `rowcounts: Dict[int, int] = {1: 0, 2: 0}` change.

**Comment by erezsh** [comment]
Thank you for contributing!

**Pull request merged**
