### PR TITLE
Switch database connectors to sqeleton

### PR DESCRIPTION
**Pull request by williebsweet**
Switch the connector docs from data-diff to sqeleton - e.g. `pip install 'data-diff[snowflake]'` to `pip install 'sqeleton[snowflake]'`

### CODE REVIEW

**Comment by erezsh** [comment]
I'm not sure this is necessary. The current plan is to support both ways, and the current way is probably less confusing. Also, it allows users to install everything at once, instead of installing data-diff, and then `sqeleton[...]` separately.

**Comment by williebsweet** [comment]
So you can still use `pip install 'data-diff[snowflake]'`?

**Comment by erezsh** [comment]
Yes, should work.

**Comment by williebsweet** [comment]
Confirmed it works. 

However, if you don't have the connector installed the CLI will prompt you to install `'sqeleton[snowflake]'`. Might be good to change that in the future.

**Pull request closed without merging**
