### PR TITLE
add redshift, postgres, databricks support

### PR DESCRIPTION
**Pull request by dlawin**
Adds conn parsing for redshift, postgres, databricks

Note that I changed the max supported version constant. We can't support dbt versions >= 1.4.2 as the manifest.json doesn't align with the posted json schema

### CODE REVIEW

**Review by williebsweet — APPROVED** [review]

**Comment by bolinzzz** [comment]
Hi team, I followed the instructions [here](https://docs.datafold.com/os_diff/dbt_integration) for dbt integration (Redshift)

When I did ` pip install data-diff 'data-diff[redshift]' -U`, I received the following warning message:
`WARNING: data-diff 0.6.0 does not provide the extra 'redshift'` 

Also when I tried running `data-diff --dbt`, I am getting the following errors:
```                                  
[16:46:33] WARNING - Failure while finding unique cols: list index out of range
[16:46:33] WARNING - Failure while finding unique cols: list index out of range
[16:46:33] WARNING - Failure while finding unique cols: list index out of range
[16:46:33] WARNING - Failure while finding unique cols: list index out of range
Running with data-diff=0.6.0

[16:46:33] ERROR - Only password authentication is currently supported for Redshift.
```
Could you advise me how to proceed with this, thanks!

**Comment by williebsweet** [comment]
@bolinzzz this might be an error in our docs (cc @dlawin). I think redshift actually uses the postgres connector. Can you try installing that?

**Comment by dlawin** [comment]
@bolinzzz 
> [16:46:33] ERROR - Only password authentication is currently supported for Redshift.

Is this the connection method you are using for dbt redshift? https://docs.getdbt.com/reference/warehouse-setups/redshift-setup#password-based-authentication

**Comment by bolinzzz** [comment]
Thank you for looking into this! 
@dlawin Yeap, I have been using password-based authentication, here's the skeleton for my dbt profile at `~/.dbt/profiles.yml`:
```

default:
  outputs:
    no_prefix:
      type: redshift
      threads: 
      host: 
      port: 
      user: 
      pass: 
      dbname: 
      schema: 
```

@williebsweet getting the same errors with postgres connector.

**Comment by dlawin** [comment]
> Thank you for looking into this! @dlawin Yeap, I have been using password-based authentication, here's the skeleton for my dbt profile at `~/.dbt/profiles.yml`:
> 
> ```
> 
> default:
>   outputs:
>     no_prefix:
>       type: redshift
>       threads: 
>       host: 
>       port: 
>       user: 
>       pass: 
>       dbname: 
>       schema: 
> ```
> 
```
      pass: 
```
We're expecting the password to be named `password: `, I'm surprised this works with dbt given I don't see it here https://docs.getdbt.com/reference/warehouse-setups/redshift-setup

I'll open an issue to add `pass: ` as an alternate key, but if you'd like to use this in the interim, `password: ` should work.

**Pull request merged**
