### PR TITLE
add json format for dbt diff values

### PR DESCRIPTION
**Pull request by vvkh**
Add `--json-output` parameter support for dbt diffs. See type hints in `data_diff/format.py` and `tests/test_format.py` for documentation of the format.

Main things to discuss @nolar @dagadbm 
* For what is already being shown, are we happy with the current format?
* Is there anything important you can think of that is missing in the current format?

### CODE REVIEW

**Comment by dlawin** [comment]
I'm getting an exception
```
  File "/Users/dan/repos/data-diff/data_diff/info_tree.py", line 21, in SegmentInfo
    def set_diff(self, diff: list[tuple[Any, ...]], schema: tuple[tuple[str, type]] | None = None):
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
```

**Comment by vvkh** [comment]
@dagadbm forgot that those type hints were not supported by the older versions of Python. I just pushed a fix.

**Comment by dlawin** [comment]
I'm seeing this when I run against it the test project:

```
  File "/Users/dan/repos/data-diff/data_diff/dbt.py", line 130, in dbt_diff
    _local_diff(diff_vars, json_output)
  File "/Users/dan/repos/data-diff/data_diff/dbt.py", line 286, in _local_diff
    jsonify(
  File "/Users/dan/repos/data-diff/data_diff/format.py", line 24, in jsonify
    schema = [field for field, _ in diff_info.diff_schema]
TypeError: 'NoneType' object is not iterable
```
`poetry run python -m data_diff --dbt --dbt-project-dir tests/dbt_artifacts --dbt-profiles-dir tests/dbt_artifacts --json`

**Comment by vvkh** [comment]
@dlawin I've added a fix for the exception you mentioned, thanks for the hint how to solve it 🙇

**Review by dlawin — APPROVED** [review]

**Comment by dlawin** [comment]
Resolves #607

**Pull request merged**
